networks:
  fosdem2026:
    external: true
    name: fosdem2026

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    networks:
      - fosdem2026
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=fosdem
      - DOCKER_INFLUXDB_INIT_ORG=fosdem
      - DOCKER_INFLUXDB_INIT_BUCKET=fosdem2026
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=13NSkxbvAnGSbQIHAzWAQFsNVDXWHD94-NG2taWgmFCJ1FiLiFjjwNe_Vg37sKUc2Cn_kSWYMCR0egexhp3PRg==

  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3000:3000"
    networks:
      - fosdem2026
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

  postgres:
    image: postgres:15
    networks:
      - fosdem2026
    environment:
      POSTGRES_DB: instrumentation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    networks:
      - fosdem2026
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - fosdem2026
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT:-}
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    ports:
      # Some ports are optional or deprecated, but we still let them be here as it's a general snippet
      - "5775:5775/udp" # agent accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - "6831:6831/udp" # agent accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # agent accept jaeger.thrift over binary thrift protocol
      - "5778:5778" # agent serve configs
      - "16686:16686" # query serve frontend (Jaeger UI)
      - "14268:14268" # collector accept jaeger.thrift directly from clients
      - "14250:14250" # collector accept model.proto
      - "9411:9411" # collector Zipkin compatible endpoint (optional)
      # - "4317:4317" # OTLP collector grpc (commented out - OTEL collector uses these ports)
      # - "4318:4318" # OTLP collector http (commented out - OTEL collector uses these ports)

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yaml", "--feature-gates=-exporter.datadogexporter.DisableAPMStats" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - fosdem2026
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - GRAFANA_ENDPOINT=${GRAFANA_ENDPOINT}
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
    depends_on:
      - jaeger
      - prometheus

volumes:
  postgres_data:
